@startuml
title: 用户登陆泳道图
|登陆模块|
start
:用户登陆;
if (是否已注册) then(yes)
   repeat
   :登陆;
   repeat while (用户名、密码是否正确?)
   :进入系统;
   stop
else(no)
|注册模块|
  repeat
   :注册;
   repeat while (用户名是否合法?)
   :注册成功;
stop
@enduml